name: RSpec Test Matrix
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres
        env:
          POSTGRES_DB: test_active_record_union
          POSTGRES_USER: active_record_union
          POSTGRES_PASSWORD: active_record_union

      mysql2:
        image: mysql:8.0
        env:
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: test_active_record_union
          MYSQL_USER: active_record_union
          MYSQL_PASSWORD: active_record_union
          MYSQL_ROOT_PASSWORD: active_record_union
    strategy:
      fail-fast: false
      matrix:
#        rails: ["5.2", "6.0", "6.1", "7.0", "7.1", "7.2", "8.0"]
#        ruby: ["2.5", "2.6", "3.0", "3.1", "3.2", "3.3"]
        # just define specific versions for each rails version
        include:
          - ruby: 2.5
            rails: 5.2
          - ruby: 2.6
            rails: 6.0
          - ruby: 3.0
            rails: 6.1
          - ruby: 3.1
            rails: 7.0
          - ruby: 3.2
            rails: 7.1
          - ruby: 3.2
            rails: 7.2
          - ruby: 3.3
            rails: 8.0

    env:
      BUNDLE_GEMFILE: "rails_${{ matrix.rails }}.gemfile"
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # install gems and cache

      - run: bundle install
      - run: bundle exec rspec
