name: RSpec Test Matrix
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rails: ["7.0", "7.1", "7.2", "8.0"]
        ruby: ["3.1", "3.2", "3.3"]
    env:
      BUNDLE_GEMFILE: "rails_${{ matrix.rails }}.gemfile"
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # install gems and cache

      - run: bundle install
      - run: bundle exec rspec
